import {
  WelcomeScreen,
  LoginScreen,
  SignupScreen,
  ForgotPwdScreen,
  SucefullyCodeScreen,
  NewPwdScreen,
  SucefullyNewPwdScreen,
  TutorialScreen,
  SetUsernameScreen,
  SetGenderScreen,
  SetBirthScreen,
  SetPhotoScreen,
  SetZipCodeScreen,
  SetLocationDataScreen,
  SetNumberBioScreen,
  SetMusicalTasteScreen,
  HomePage,
  StoryScreen,
} from "./AppPages";

export const screenData = [
  { name: "Welcome", component: WelcomeScreen },
  { name: "Login", component: LoginScreen },
  { name: "Signup", component: SignupScreen },
  { name: "ForgotPwd", component: ForgotPwdScreen },
  { name: "SucefullyCode", component: SucefullyCodeScreen },
  { name: "NewPwd", component: NewPwdScreen },
  { name: "SucefullyNewPwd", component: SucefullyNewPwdScreen },
  { name: "Tutorial", component: TutorialScreen },
  { name: "SetUsername", component: SetUsernameScreen },
  { name: "SetGender", component: SetGenderScreen },
  { name: "SetBirth", component: SetBirthScreen },
  { name: "SetPhoto", component: SetPhotoScreen },
  { name: "SetZipCode", component: SetZipCodeScreen },
  { name: "SetLocationData", component: SetLocationDataScreen },
  { name: "SetNumberBio", component: SetNumberBioScreen },
  { name: "SetMusicalTaste", component: SetMusicalTasteScreen },
  { name: "HomePage", component: HomePage },
  { name: "StoryScreen", component: StoryScreen },
];
